name: Deploy to GitHub Pages on push to master
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Setup markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Check markdown
        run: markdownlint content

      - name: Deploy the site
        uses: benmatselby/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: 0.74.2
          TARGET_REPO: eugenix/eugenix.github.io
          TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          HUGO_ARGS: ''
          CNAME: jekurb.dev

      - name: Run smoke tests
        env:
          BLOG_BASE_URL: https://jekurb.dev
        run: cd smoke-tests && npm install && npm test

#      - name: If fail revert changes

#      - name: Notify me


